services:

  auth_db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - aivent-net

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - aivent-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - aivent-net

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    depends_on:
      - auth_db
      - rabbitmq
      - redis
    env_file:
      - ./auth-service/.env
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service/media:/app/media
      - ./auth-service/keys/private.pem:/app/keys/private.pem
      - ./auth-service/keys/public.pem:/app/keys/public.pem
    networks:
      - aivent-net
    command: >
      sh -c "
        /wait-for-db.sh auth_db 5432;
        python manage.py migrate;
        python manage.py runserver 0.0.0.0:8000
      "

  auth_celery_worker:
    build:
      context: ./auth-service
    command: celery -A auth_project worker --loglevel=info --concurrency=2
    depends_on:
      - auth-service
      - rabbitmq
      - redis
    env_file:
      - ./auth-service/.env
    networks:
      - aivent-net

  auth_celery_beat:
    build:
      context: ./auth-service
    command: celery -A auth_project beat --loglevel=info
    depends_on:
      - auth-service
      - rabbitmq
      - redis
    env_file:
      - ./auth-service/.env
    networks:
      - aivent-net

  vendor_db:
    image: postgres:15
    environment:
      POSTGRES_DB: vendor_db
      POSTGRES_USER: vendor
      POSTGRES_PASSWORD: vendorpass
    ports:
      - "5436:5432"
    volumes:
      - vendor_db_data:/var/lib/postgresql/data
    networks:
      - aivent-net

  vendor-service:
    build:
      context: ./vendor-service
    depends_on:
      - vendor_db
      - rabbitmq
    env_file:
      - ./vendor-service/.env
    volumes:
      - ./auth-service/keys/public.pem:/app/keys/public.pem:ro
    ports:
      - "8002:8000"
    networks:
      - aivent-net
    command: >
      sh -c "
        /wait-for-db.sh vendor_db 5432;
        python manage.py migrate;
        python manage.py runserver 0.0.0.0:8000 --noreload
      "


  vendor_celery_worker:
    build:
      context: ./vendor-service
    command: celery -A vendor_project worker -Q vendor --loglevel=info
    depends_on:
      - vendor-service
      - rabbitmq
      - redis
    env_file:
      - ./vendor-service/.env
    volumes:
      - ./auth-service/keys/public.pem:/app/keys/public.pem:ro
    networks:
      - aivent-net


  vendor_consumer:
    build:
      context: ./vendor-service
    depends_on:
      - vendor_db
      - rabbitmq
    env_file:
      - ./vendor-service/.env
    volumes:
      - ./auth-service/keys/public.pem:/app/keys/public.pem:ro
    networks:
      - aivent-net
    command: >
      sh -c "
        python vendor_app/consumers/vendor_events.py
      "

  catalog_db:
      image: postgres:15
      environment:
        POSTGRES_DB: catalog_db
        POSTGRES_USER: catalog
        POSTGRES_PASSWORD: catalogpass
      ports:
        - "5437:5432"
      volumes:
        - catalog_db_data:/var/lib/postgresql/data
      networks:
        - aivent-net


  catalog-service:
    build:
      context: ./catalog-service
    depends_on:
      - catalog_db
    env_file:
      - ./catalog-service/.env
    ports:
      - "8003:8000"
    volumes:
      - ./auth-service/keys/public.pem:/app/keys/public.pem:ro
    networks:
      - aivent-net
    command: >
      sh -c "
        python manage.py migrate;
        python manage.py runserver 0.0.0.0:8000 --noreload
      "



networks:
  aivent-net:

volumes:
  auth_db_data:
  vendor_db_data:
  catalog_db_data: