apiVersion: v1
kind: ConfigMap
metadata:
  name: core-service-config
data:
  DJANGO_SETTINGS_MODULE: "core_service.settings"
  DEBUG: "false"

  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "core_db"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"

  AUTH_SERVICE_URL: "http://auth-service"
