apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: sinanpk/core-service:latest
          imagePullPolicy: IfNotPresent

          command: ["gunicorn"]

          args:
          - "core.wsgi:application"
          - "--bind"
          - "0.0.0.0:8000"
          - "--workers"
          - "2"


          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: core-service-config
            - secretRef:
                name: core-service-secrets

          volumeMounts:
            - name: jwt-public-key
              mountPath: /app/keys
              readOnly: true

          readinessProbe:
            httpGet:
              path: /api/bookings/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/bookings/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: jwt-public-key
          secret:
            secretName: core-service-keys
